### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by abidrazaa**

### CODE REVIEW

**Comment by UsamaSarwar** [comment]
Please add a Screenshot Folder with screenshots of changes and update them as well in future when you update the UI.

- screenshot
  - loginScreen.jpg
  - signupScreen.jpg
  - forgetScreen.jpg

**Comment by abidrazaa** [comment]
> Please add a Screenshot Folder with screenshots of changes and update them as well in future when you update the UI.
> 
> * screenshot
>   
>   * loginScreen.jpg
>   * signupScreen.jpg
>   * forgetScreen.jpg

Added.

**Comment by UsamaSarwar** [comment]
> > Please add a Screenshot Folder with screenshots of changes and update them as well in future when you update the UI.
> > 
> > * screenshot
> >   
> >   * loginScreen.jpg
> >   * signupScreen.jpg
> >   * forgetScreen.jpg
> 
> Added.

Can you please PR again? This had some conflicts.

**Comment by abidrazaa** [comment]
> > > Please add a Screenshot Folder with screenshots of changes and update them as well in future when you update the UI.
> > > 
> > > * screenshot
> > >   
> > >   * loginScreen.jpg
> > >   * signupScreen.jpg
> > >   * forgetScreen.jpg
> > 
> > 
> > Added.
> 
> Can you please PR again? This had some conflicts.

Yes. Doing.

**Comment by abidrazaa** [comment]
> > > > Please add a Screenshot Folder with screenshots of changes and update them as well in future when you update the UI.
> > > > 
> > > > * screenshot
> > > >   
> > > >   * loginScreen.jpg
> > > >   * signupScreen.jpg
> > > >   * forgetScreen.jpg
> > > 
> > > 
> > > Added.
> > 
> > 
> > Can you please PR again? This had some conflicts.
> 
> Yes. Doing.

All good? Merged successfully?

**Comment by UsamaSarwar** [comment]
Yea 🙌🏻

**Pull request merged**
